### ISSUE TITLE
unknown opcodes/structures?

### ISSUE THREAD

**Issue by FZFalzar** [Rerumu/Lida#1]
Been hunting all over for a C# implementation of a lua51 decompiler until I found yours, great work so far!

However I've come up with several issues while debugging the tool which I have narrowed down to either unknown opcode or control structure bugs. ChunkSpy is reporting no errors though.

 I'm not sure if this is due to the target using a variant of Lua 5.1. Of course, I don't have the original source to compare to ;) some sample luacs are attached:
[sample.zip](https://github.com/Rerumu/Lida/files/1802386/sample.zip)

Looking forward to the decompiler!
-Falz

**Comment by Rerumu** [comment]
I'll look into it as soon as I can, thanks for notifying me.

**Comment by Rerumu** [comment]
Upon closer inspection, it seems the instructions in the files aren't formatted according to the Lua header accompanying them, so I can't really help on this.
`luac -l` seems to come up with `bad code in precompiled chunk`, so ChunkSpy working is just convenient.

**Comment by FZFalzar** [comment]
I see, guess I'll have to RE the engine itself and see what's changed, thanks for your insight!

**Comment by FZFalzar** [comment]
Just a followup regarding my issue, its highly likely due to a case of lua_tinker (https://github.com/zupet/LuaTinker) acting on and slightly modifying the behavior of the luaL_loadstring API which is used to load chunks from strings

**Comment by Rerumu** [comment]
I do have plans on adding easier ways to modify the core so that it's made possible to debug altered bytecode, but no promises as of right now. As for that specific instance, I may look into it when I have some time.
